In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import numpy as npp

arr = npp.array([1 , 2 , 3 , 4 , 5 ,6 , 7 ]) #1D Array
print(arr)


print(arr[2])

print(arr[0:2])  #slicing a array
print(arr[0:6 : 2])
arr1 = npp.array([[1 , 3 , 5] , [3 ,4 , 63] , [2 ,3 ,5 ]]) #2D array
print(arr1)


print(arr1[0,2])
print(arr1[0,:1])
print(arr1[0,:1])

print(arr1[0:2 , 1:3]) #for specific colomun and row 

print(arr1[0:3 : 2 , 0:3 : 2])

[1 2 3 4 5 6 7]
3
[1 2]
[1 3 5]
[[ 1  3  5]
 [ 3  4 63]
 [ 2  3  5]]
5
[1]
[1]
[[ 3  5]
 [ 4 63]]
[[1 5]
 [2 5]]


In [3]:
#array reshaping

arr = npp.array([1,2 ,3,4,5,6])
print(arr)
newrr=arr.reshape(3,2)
print(newrr)
newrr=arr.reshape(2,3)
print(newrr)

newrr=arr.reshape(6,1)
print(newrr)

newrr=arr.reshape(1,6)
print(newrr)

newrr=arr.reshape(3,1,2)
print(newrr)



[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [4]:



arr = npp.array([1,2 ,3,4,5,6 , 7 ,8 ,9 , 10 , 11 , 12])
print(arr)
newrr=arr.reshape(2,6)
print(newrr)
newrr=arr.reshape(3,4)
print(newrr)

newrr=arr.reshape(4,3)
print(newrr)

newrr=arr.reshape(6,2)
print(newrr)



newrr=arr.reshape(1,12)
print(newrr)

newrr=arr.reshape(12,1)
print(newrr)
newrr=arr.reshape(6,1,2)   # converting in 3D matrix
print(newrr)

newrr=arr.reshape(3,2,2)  # converting in 3D matrix
print(newrr)

newrr=arr.reshape(2,3,2)  # converting in 3D matrix
print(newrr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
 newrr=arr.reshape(2,3,2)  # converting in 3D matrix
print(newrr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
print(newrr[1,2,0])

11


In [7]:
print(newrr[1,0:3])

[[ 7  8]
 [ 9 10]
 [11 12]]


In [8]:
newrr=arr.reshape(2,2,3)  # converting in 3D matrix
print(newrr)

print(newrr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [9]:


m = np.array([55 , 60 , 72 , 88 , 85 , 90 , 95])

Q1 = np.percentile(m, 25)
Q3 = np.percentile(m, 75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = m[(m < lower) | (m > upper)]

print(outliers)


[]


In [10]:
arr = np.array([10 , 20 , 30])
p = arr.view()
print(p)

arr[2] = 34
print(p)

[10 20 30]
[10 20 34]


In [11]:
# Date : 27-09-26

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3))



np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
#Pandas Example

import pandas as pf

ia = pf.DataFrame({
    'Student' : [ 'A' , 'B ', 'C' , 'D'],
     'Math'  : [ 62 , 52 , 87 , 92 ],
     'CSE' :  [ 45 , 85 , 98 , 48 ] ,
'English' :  [ 75 , 85 , 78 , 58 ] ,
'Grade' :  [ 'A' ,'A' , 'B ' , 'C' ] 

}) 
print(ia)

  Student  Math  CSE  English Grade
0       A    62   45       75     A
1      B     52   85       85     A
2       C    87   98       78    B 
3       D    92   48       58     C


In [17]:
f = ia[['Math' , 'CSE' , 'English']].values
print(f)
print(len(f))

a = f[0]    #list are they
b = f[1]
print(a,b)

[[62 45 75]
 [52 85 85]
 [87 98 78]
 [92 48 58]]
4
[62 45 75] [52 85 85]


In [18]:
#Manhattan

import numpy as np


dissimilarityM = np.zeros((len(f), len(f)))

for i in range(len(f)):
  for j in range(len(f)):
    dissimilarityM[i][j] = np.sum(np.abs(f[i]-f[j]))
      
    
print(dissimilarityM)



[[  0.  60.  81.  50.]
 [ 60.   0.  55. 104.]
 [ 81.  55.   0.  75.]
 [ 50. 104.  75.   0.]]


In [19]:
#Eucleadian


dissimilarityEucleadian = np.zeros((len(f), len(f)))

for i in range(len(f)):
  for j in range(len(f)):
    dissimilarityEucleadian[i][j] = np.sqrt(np.sum(f[i]-f[j]) ** 2)
      
    
print(dissimilarityEucleadian)


[[ 0. 40. 81. 16.]
 [40.  0. 41. 24.]
 [81. 41.  0. 65.]
 [16. 24. 65.  0.]]


In [20]:
 #Finding the dissimilarity of nominal and ordian matrix


#Pandas Example

import pandas as pf

ia = pf.DataFrame({
    'Student' : [ 'A' , 'B ', 'C' , 'D'],
     'Math'  : [ 62 , 52 , 87 , 92 ],
     'CSE' :  [ 45 , 85 , 98 , 48 ] ,
'English' :  [ 75 , 85 , 78 , 58 ] ,
'Grade' :  [ 'A' ,'A' , 'B ' , 'C' ] 

}) 
print(ia)


nominal_dissimilariy =np.zeros((len(f), len(f)))

for i in range(len(f)):
  for j in range(len(f)):
   nominal_dissimilariy[i][j] = 1 -  np.sqrt(np.sum(f[i]-f[j]) ** 2)


print(nominal_dissimilariy)

  Student  Math  CSE  English Grade
0       A    62   45       75     A
1      B     52   85       85     A
2       C    87   98       78    B 
3       D    92   48       58     C
[[  1. -39. -80. -15.]
 [-39.   1. -40. -23.]
 [-80. -40.   1. -64.]
 [-15. -23. -64.   1.]]


In [21]:

ia = pd.DataFrame({
    'Student' : [ 'A' , 'B ', 'C' , 'D'],
    'Math'    : [ 62 , 52 , 87 , 92 ],
    'CSE'     : [ 45 , 85 , 98 , 48 ] ,
    'English' : [ 75 , 85 , 78 , 58 ] ,
    'Grade'   : [ 'A' ,'A' , 'B ' , 'C' ] 
}) 


c = ['Math', 'CSE', 'English']
f = ia[c].values


p = len(c)
n = len(f)


nominal_dissimilarity = np.zeros((n, n))

for i in range(n):
    for j in range(n):
 
        m = np.sum(f[i] == f[j])
        nominal_dissimilarity[i, j] = (p - m) / p

print("Nominal Dissimilarity Matrix:\n", nominal_dissimilarity )
print()


Nominal Dissimilarity Matrix:
 [[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]



In [22]:


ia = pd.DataFrame({
    'Student' : [ 'A' , 'B ', 'C' , 'D'],
    'Math'    : [ 62 , 52 , 87 , 92 ],
    'CSE'     : [ 45 , 85 , 98 , 48 ] ,
    'English' : [ 75 , 85 , 78 , 58 ] ,
    'Grade'   : [ 'A' ,'A' , 'B ' , 'C' ] 
}) 



g = {'C': 1, 'B': 2, 'A': 3}
ranks = ia['Grade'].str.strip().map(g).values

small = min(g.values())
M = max(g.values())
z = (ranks - small) / (M - small)

n = len(z)
ordinal_dissimilarity = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        ordinal_dissimilarity[i, j] = np.abs(z[i] - z[j])

print(ordinal_dissimilarity)

[[0.  0.  0.5 1. ]
 [0.  0.  0.5 1. ]
 [0.5 0.5 0.  0.5]
 [1.  1.  0.5 0. ]]


In [23]:
print("Nominal similarity Matrix:\n", 1-nominal_dissimilarity )

Nominal similarity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
print("Nominal similarity Matrix:\n", 1-ordinal_dissimilarity )

Nominal similarity Matrix:
 [[1.  1.  0.5 0. ]
 [1.  1.  0.5 0. ]
 [0.5 0.5 1.  0.5]
 [0.  0.  0.5 1. ]]
