In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [33]:
import numpy as npp

arr = npp.array([1 , 2 , 3 , 4 , 5 ,6 , 7 ]) #1D Array
print(arr)


print(arr[2])

print(arr[0:2])  #slicing a array
print(arr[0:6 : 2])
arr1 = npp.array([[1 , 3 , 5] , [3 ,4 , 63] , [2 ,3 ,5 ]]) #2D array
print(arr1)


print(arr1[0,2])
print(arr1[0,:1])
print(arr1[0,:1])

print(arr1[0:2 , 1:3]) #for specific colomun and row 

print(arr1[0:3 : 2 , 0:3 : 2])

[1 2 3 4 5 6 7]
3
[1 2]
[1 3 5]
[[ 1  3  5]
 [ 3  4 63]
 [ 2  3  5]]
5
[1]
[1]
[[ 3  5]
 [ 4 63]]
[[1 5]
 [2 5]]


In [49]:
#array reshaping

arr = npp.array([1,2 ,3,4,5,6])
print(arr)
newrr=arr.reshape(3,2)
print(newrr)
newrr=arr.reshape(2,3)
print(newrr)

newrr=arr.reshape(6,1)
print(newrr)

newrr=arr.reshape(1,6)
print(newrr)

newrr=arr.reshape(3,1,2)
print(newrr)



[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [52]:



arr = npp.array([1,2 ,3,4,5,6 , 7 ,8 ,9 , 10 , 11 , 12])
print(arr)
newrr=arr.reshape(2,6)
print(newrr)
newrr=arr.reshape(3,4)
print(newrr)

newrr=arr.reshape(4,3)
print(newrr)

newrr=arr.reshape(6,2)
print(newrr)



newrr=arr.reshape(1,12)
print(newrr)

newrr=arr.reshape(12,1)
print(newrr)
newrr=arr.reshape(6,1,2)   # converting in 3D matrix
print(newrr)

newrr=arr.reshape(3,2,2)  # converting in 3D matrix
print(newrr)

newrr=arr.reshape(2,3,2)  # converting in 3D matrix
print(newrr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [53]:
 newrr=arr.reshape(2,3,2)  # converting in 3D matrix
print(newrr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [56]:
print(newrr[1,2,0])

11


In [57]:
print(newrr[1,0:3])

[[ 7  8]
 [ 9 10]
 [11 12]]


In [61]:
newrr=arr.reshape(2,2,3)  # converting in 3D matrix
print(newrr)

print(newrr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [67]:


m = np.array([55 , 60 , 72 , 88 , 85 , 90 , 95])

Q1 = np.percentile(m, 25)
Q3 = np.percentile(m, 75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = m[(m < lower) | (m > upper)]

print(outliers)


[]


In [70]:
arr = np.array([10 , 20 , 30])
p = arr.view()
print(p)

arr[2] = 34
print(p)

[10 20 30]
[10 20 34]
