In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [37]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Student': ['Akash', 'Bithi', 'Choyon', 'Disha'],
    'Attendance': ['R','NR','R','R'],
    'Gender': ['M','F','M','F'],
    'Math': [80, 82, 40, 20],
    'CSE': [70, 72, 50, 25],
    'English': [90, 88, 45, 15],
    'Grade': ['A','A','B', 'C']
})  

print(df)


  Student Attendance Gender  Math  CSE  English Grade
0   Akash          R      M    80   70       90     A
1   Bithi         NR      F    82   72       88     A
2  Choyon          R      M    40   50       45     B
3   Disha          R      F    20   25       15     C


In [38]:
# Find the similarity matrix of numeric attributes
# Find the dissimilarity matrix of Nominal attributes
# Find the dissimilarity matrix of binary attributes
# Find the dissimilarity matrix of ordinal attributes

In [39]:
#1
f = df[['Math' , 'CSE' , 'English']].values

ds = np.zeros((len(f), len(f)))

for i in range (len(f)):
 for j in range (len(f)):
     ds[i][j] = np.sum(np.abs(f[i]-f[j]))


 print(ds)




[[  0.   6. 105. 180.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0.   6. 105. 180.]
 [  6.   0. 107. 182.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0.   6. 105. 180.]
 [  6.   0. 107. 182.]
 [105. 107.   0.  75.]
 [  0.   0.   0.   0.]]
[[  0.   6. 105. 180.]
 [  6.   0. 107. 182.]
 [105. 107.   0.  75.]
 [180. 182.  75.   0.]]


In [40]:
#2


c = ['Attendance', 'Gender', ]
f = df[c].values


p = len(c)
n = len(f)


nd = np.zeros((n, n))

for i in range(n):
    for j in range(n):
 
        m = np.sum(f[i] == f[j])
        nd[i, j] = (p - m) / p

print("Nominal Dissimilarity Matrix:\n", nd )



Nominal Dissimilarity Matrix:
 [[0.  1.  0.  0.5]
 [1.  0.  1.  0.5]
 [0.  1.  0.  0.5]
 [0.5 0.5 0.5 0. ]]


In [41]:
#3



g = {'C': 3, 'B': 2, 'A': 1}
ranks = df['Grade'].str.strip().map(g).values

small = min(g.values())
M = max(g.values())
z = (ranks - small) / (M - small)

n = len(z)
ordinal_dissimilarity = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        ordinal_dissimilarity[i, j] = np.abs(z[i] - z[j])

print(ordinal_dissimilarity)

[[0.  0.  0.5 1. ]
 [0.  0.  0.5 1. ]
 [0.5 0.5 0.  0.5]
 [1.  1.  0.5 0. ]]


In [42]:
import pandas as pd
import numpy as np

# Select binary attributes
bi = df[['Attendance', 'Gender']].copy()

# Convert binary values to 0 and 1
bi['Attendance'] = bi['Attendance'].map({
    'R': 1,
    'NR': 0
})

bi['Gender'] = bi['Gender'].map({
    'M': 1,
    'F': 0
})

# Create an empty dissimilarity matrix
n = len(bi)
ds = np.zeros((n, n))

# Calculate dissimilarity
for i in range(n):
    for j in range(n):
        differences = np.sum(bi.iloc[i] != bi.iloc[j])
        ds[i][j] = differences / len(bi.columns)

# Display the result
print("Binary Dissimilarity Matrix:")
print(ds)


Binary Dissimilarity Matrix:
[[0.  1.  0.  0.5]
 [1.  0.  1.  0.5]
 [0.  1.  0.  0.5]
 [0.5 0.5 0.5 0. ]]
